# Inbuilt Functions

In [2]:
# date
# get the current date and time

import datetime

x = datetime.datetime.now()
print(x)


2020-06-17 12:31:13.824784


In [3]:
print(x.year)
print(x.strftime("%A"))

2020
Wednesday


In [4]:
# create date
x = datetime.datetime(2018,6,1)
print(x.strftime("%B"))

June


In [5]:
import time # this is required to time module

ticks = time.time()
ticks
print("Number of ticks since 12:00 am , Jan, 1970 :", ticks)

Number of ticks since 12:00 am , Jan, 1970 : 1592377276.3659213


In [6]:
localtime = time.localtime(time.time())
print("Local current time :", localtime)

Local current time : time.struct_time(tm_year=2020, tm_mon=6, tm_mday=17, tm_hour=12, tm_min=31, tm_sec=16, tm_wday=2, tm_yday=169, tm_isdst=0)


In [7]:
# formatted time

localtime = time.asctime(time.localtime(time.time()))
print("Local Current time :", localtime)

Local Current time : Wed Jun 17 12:31:17 2020


In [8]:
# Calender

import calendar

cal= calendar.month(2020,6)
print("June 2020 Calendar :")
print(cal)

June 2020 Calendar :
     June 2020
Mo Tu We Th Fr Sa Su
 1  2  3  4  5  6  7
 8  9 10 11 12 13 14
15 16 17 18 19 20 21
22 23 24 25 26 27 28
29 30



# Introduction to Numpy

In [9]:
# Numpy , stands for numerical python

import numpy as np


In [10]:
## create a tuple and convert into array
tu = (1,2,3)
type(tu)
out_tu = np.array(tu)
print("out_tu", out_tu)
print("out_tu_type",type(out_tu))

out_tu [1 2 3]
out_tu_type <class 'numpy.ndarray'>


In [11]:
# create a list and convert into an array

imp =[20.1,20.8,21.9,33.4,33.5,11.5,20.1]
type(imp)

list

In [12]:
# convert the values into one dim array 

out = np.array(imp)
print(out)
print(out.shape) # chk for dim
print(type(out)) # chk for the datatype

[ 20.1  20.8  21.9  33.4  33.5  11.5  20.1]
(7,)
<class 'numpy.ndarray'>


In [13]:
len(out)

7

In [14]:
# create a seq num in array

sq = np.arange(9)
print(sq)
print(sq.ndim)
print(sq.shape)

[0 1 2 3 4 5 6 7 8]
1
(9,)


In [15]:
my_array = np.arange(9)

# print the number of 'my_array' dimensions
print(my_array.ndim)

# print the number of elements
print(my_array.size)

#print the length of array elements in bytes
print(my_array.itemsize)

#print the total consumed bytes if array elements
print(my_array.nbytes)

1
9
8
72


In [16]:
# print the length of "My_array"

import numpy as np

my_array = np.arange(9)
print(my_array)
print(len(my_array))
print(type(my_array))


# change the datatype of thr array

print(my_array.astype(float))

[0 1 2 3 4 5 6 7 8]
9
<class 'numpy.ndarray'>
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.]


In [17]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
np.arange(5,25)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [19]:
np.arange(0,15,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

# linspace

In [20]:
a = np.linspace(1,5,num=4)
print(a)

[ 1.          2.33333333  3.66666667  5.        ]


In [21]:
# create an array of evenly spaced values

np.linspace(0,2,4) #start #end # num of split

array([ 0.        ,  0.66666667,  1.33333333,  2.        ])

In [22]:
print(np.linspace(1.0,5.0,num=5,endpoint=True))

[ 1.  2.  3.  4.  5.]


In [23]:
sq = np.arange(1,10)
b = sq.reshape(1,3,3) # 1 matrix 2 rows 2 col
print(b)
type(b)
print(sq.size)
print(sq.ndim)
print(sq.item)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
9
1
<built-in method item of numpy.ndarray object at 0x7efe4d2f9990>


In [24]:
import numpy as np
sq = np.arange(1,25)
print(sq)
print(sq.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
(24,)


In [25]:
b = sq.reshape(2,4,3) # 2 matrix, 4 rows , 3 columns

In [26]:
b

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [27]:
print(sq.ndim)

1


In [28]:
print(sq.size)
print(sq.item)

24
<built-in method item of numpy.ndarray object at 0x7efe4d2f9df0>


In [29]:
c = sq.reshape(1,4,6)
c

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]])

In [30]:
arr_1 = np.array([1,2,3])
print(arr_1)
print(arr_1.shape)

[1 2 3]
(3,)


In [31]:
arr_2 = np.array([[1,2,3],[4,5,6]])
print(arr_2)

[[1 2 3]
 [4 5 6]]


In [32]:
arr_3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
x = np.ones((3,4))
print(x)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [34]:
y = np.random.random((1,3,4))
print(y)

[[[ 0.18914178  0.75737655  0.37669431  0.08007021]
  [ 0.00110737  0.63476973  0.29911485  0.84598802]
  [ 0.71332518  0.86752415  0.33046764  0.29988865]]]


In [35]:
z = np.random.randint(5,50,4)
print(z)

[13 41 34  6]


In [36]:
np.random.randint(0,50,3)

array([ 8, 35, 29])

In [37]:
np.add(x,y)

array([[[ 1.18914178,  1.75737655,  1.37669431,  1.08007021],
        [ 1.00110737,  1.63476973,  1.29911485,  1.84598802],
        [ 1.71332518,  1.86752415,  1.33046764,  1.29988865]]])

In [38]:
np.subtract(x,y)

array([[[ 0.81085822,  0.24262345,  0.62330569,  0.91992979],
        [ 0.99889263,  0.36523027,  0.70088515,  0.15401198],
        [ 0.28667482,  0.13247585,  0.66953236,  0.70011135]]])

In [39]:
np.multiply(x,y)

array([[[ 0.18914178,  0.75737655,  0.37669431,  0.08007021],
        [ 0.00110737,  0.63476973,  0.29911485,  0.84598802],
        [ 0.71332518,  0.86752415,  0.33046764,  0.29988865]]])

In [40]:
np.divide(x,y)

array([[[   5.28703913,    1.32034719,    2.65467247,   12.48903952],
        [ 903.03713593,    1.57537443,    3.34319747,    1.18204984],
        [   1.40188517,    1.15270566,    3.02601486,    3.33457099]]])

In [41]:
data = np.array([[10,23,0,4,5,3,2,6]])
a = np.min(data)
print(a)

0


In [42]:
b = np.max(data)
print(b)

23


# Statistics

In [43]:
# mean 

a = np.array([1,2,3,5,5])
print(a)

[1 2 3 5 5]


In [44]:
a.mean()

3.2000000000000002

In [45]:
med = np.median(a)
print(med)

3.0


In [46]:
sd = np.std(a)
print(sd)

1.6


In [47]:
f = np.array([1,2])
g = np.array([4,5])

print("f",f)
print("g",g)

np.dot(f,g)

f [1 2]
g [4 5]


14

In [48]:
a = np.zeros((2,2))
print(a)

[[ 0.  0.]
 [ 0.  0.]]


In [49]:
a = np.zeros((2,2), dtype = int)
print(a)

[[0 0]
 [0 0]]


In [50]:
b = np.ones((2,2), dtype = int)
print(b)

[[1 1]
 [1 1]]


In [51]:
 c= np.full((3,4), 7)
print(c)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [52]:
d = np.eye(3)
print(d)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [53]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)


arr2 = np.ones((3,3))
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [54]:
arr1+arr2

array([[  2.,   3.,   4.],
       [  5.,   6.,   7.],
       [  8.,   9.,  10.]])

In [55]:
arr1-arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [56]:
arr1*arr2

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [57]:
np.dot(arr1,arr2)

array([[  6.,   6.,   6.],
       [ 15.,  15.,  15.],
       [ 24.,  24.,  24.]])

# pandas

In [3]:
import numpy as np
import pandas as pd

In [4]:
from pandas import Series , DataFrame

In [5]:
ser1 = pd.Series([10,20,30,40,50])
print(ser1)
print(type(ser1))

0    10
1    20
2    30
3    40
4    50
dtype: int64
<class 'pandas.core.series.Series'>


In [6]:
ser1.values

array([10, 20, 30, 40, 50])

In [7]:
ser1.index

RangeIndex(start=0, stop=5, step=1)

In [8]:
ser2 = pd.Series([10,20,30,40,50], index = ['one','two','three','four','five'])
print(ser2)

one      10
two      20
three    30
four     40
five     50
dtype: int64


In [9]:
ser2[2]

30

In [10]:
ser2['three']

30

In [11]:
ser2[['one','three','five']]

one      10
three    30
five     50
dtype: int64

In [12]:
ser2 + 4

one      14
two      24
three    34
four     44
five     54
dtype: int64

In [13]:
ser2[ser2>30]

four    40
five    50
dtype: int64

In [14]:
xyz = {"Day" : [1,2,3,4,5,6], "Visitors" : [1000,700,6000,1000,400,300],
      "Bounce_rate" : [20,20,2,3,15,20]}

In [15]:
xyz

{'Bounce_rate': [20, 20, 2, 3, 15, 20],
 'Day': [1, 2, 3, 4, 5, 6],
 'Visitors': [1000, 700, 6000, 1000, 400, 300]}

In [16]:
ser = pd.Series(xyz)

In [17]:
ser

Bounce_rate               [20, 20, 2, 3, 15, 20]
Day                           [1, 2, 3, 4, 5, 6]
Visitors       [1000, 700, 6000, 1000, 400, 300]
dtype: object

In [18]:
df = pd.DataFrame(xyz)

In [19]:
df

Bounce_rate  Day  Visitors
0           20    1      1000
1           20    2       700
2            2    3      6000
3            3    4      1000
4           15    5       400
5           20    6       300

In [20]:
df.shape

(6, 3)

In [21]:
rows,columns = df.shape

In [22]:
rows

6

In [23]:
columns

3

In [24]:
df1 = pd.DataFrame(np.arange(25).reshape(5,5))
df1

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [25]:
df11 = pd.DataFrame(np.arange(25).reshape(5,5) , index = list("ABCDE")
                   , columns = ["col1","col2","col3","col4","col5"])
df11


col1  col2  col3  col4  col5
A     0     1     2     3     4
B     5     6     7     8     9
C    10    11    12    13    14
D    15    16    17    18    19
E    20    21    22    23    24

In [26]:
df3 = DataFrame({"COMPANY" : ["WIPRO", "CISICO","GOOGLE","FACEBOOK","INFOSYS","TCS"],
                "PRICE":[100,200,400,300,600,150],
                "TICKER":["WIP","CIS","GOOG","FB","INFO","TCS"]},
               index = list("ABCDEF")
                   , columns = ["COMPANY","PRICE","TICKER"])
df3


COMPANY  PRICE TICKER
A     WIPRO    100    WIP
B    CISICO    200    CIS
C    GOOGLE    400   GOOG
D  FACEBOOK    300     FB
E   INFOSYS    600   INFO
F       TCS    150    TCS

In [27]:
df3.PRICE

A    100
B    200
C    400
D    300
E    600
F    150
Name: PRICE, dtype: int64

In [28]:
df3.TICKER

A     WIP
B     CIS
C    GOOG
D      FB
E    INFO
F     TCS
Name: TICKER, dtype: object

In [29]:
df3[['COMPANY','TICKER']]

COMPANY TICKER
A     WIPRO    WIP
B    CISICO    CIS
C    GOOGLE   GOOG
D  FACEBOOK     FB
E   INFOSYS   INFO
F       TCS    TCS

In [30]:
df3.PRICE>200

A    False
B    False
C     True
D     True
E     True
F    False
Name: PRICE, dtype: bool

In [31]:
df3[df3.PRICE>200]

COMPANY  PRICE TICKER
C    GOOGLE    400   GOOG
D  FACEBOOK    300     FB
E   INFOSYS    600   INFO

In [32]:
df3[df3['PRICE']>200]

COMPANY  PRICE TICKER
C    GOOGLE    400   GOOG
D  FACEBOOK    300     FB
E   INFOSYS    600   INFO

In [33]:
df3['NOE'] = [1000,100,350,500,450,600]
df3

COMPANY  PRICE TICKER   NOE
A     WIPRO    100    WIP  1000
B    CISICO    200    CIS   100
C    GOOGLE    400   GOOG   350
D  FACEBOOK    300     FB   500
E   INFOSYS    600   INFO   450
F       TCS    150    TCS   600

In [34]:
df3["NOE"] = df3["NOE"] - 200
df3

COMPANY  PRICE TICKER  NOE
A     WIPRO    100    WIP  800
B    CISICO    200    CIS -100
C    GOOGLE    400   GOOG  150
D  FACEBOOK    300     FB  300
E   INFOSYS    600   INFO  250
F       TCS    150    TCS  400

In [35]:
data = pd.DataFrame({'Price' : [95,25,85,41,78], 'Ticker' : ['AXP','CSCO','DIS','MSFT','WMT'],
                     'Company' : ['American Express','Cisco','Walt Disney','Microsoft','Walmart']})

In [36]:
data

Company  Price Ticker
0  American Express     95    AXP
1             Cisco     25   CSCO
2       Walt Disney     85    DIS
3         Microsoft     41   MSFT
4           Walmart     78    WMT

In [37]:
import numpy as np
data["Logo"] = np.nan # Add a column to dataframe with null values

In [38]:
data

Company  Price Ticker  Logo
0  American Express     95    AXP   NaN
1             Cisco     25   CSCO   NaN
2       Walt Disney     85    DIS   NaN
3         Microsoft     41   MSFT   NaN
4           Walmart     78    WMT   NaN

In [39]:
del data["Logo"]
data

Company  Price Ticker
0  American Express     95    AXP
1             Cisco     25   CSCO
2       Walt Disney     85    DIS
3         Microsoft     41   MSFT
4           Walmart     78    WMT

In [40]:
data["Company"] # Access Columns

0    American Express
1               Cisco
2         Walt Disney
3           Microsoft
4             Walmart
Name: Company, dtype: object

In [41]:
data.ix[2]  #Access specific row

/home/pratiksha/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


Company    Walt Disney
Price               85
Ticker             DIS
Name: 2, dtype: object

In [42]:
newdata = data.drop(2)
newdata

Company  Price Ticker
0  American Express     95    AXP
1             Cisco     25   CSCO
3         Microsoft     41   MSFT
4           Walmart     78    WMT

In [43]:
dft = data.T
dft

0      1            2          3        4
Company  American Express  Cisco  Walt Disney  Microsoft  Walmart
Price                  95     25           85         41       78
Ticker                AXP   CSCO          DIS       MSFT      WMT

In [44]:
# Indexing

df1 = data.ix[:,"Price"]
df1

0    95
1    25
2    85
3    41
4    78
Name: Price, dtype: int64

In [45]:
data.ix[3,0]

'Microsoft'

# Indexing with iloc

In [46]:
data 

Company  Price Ticker
0  American Express     95    AXP
1             Cisco     25   CSCO
2       Walt Disney     85    DIS
3         Microsoft     41   MSFT
4           Walmart     78    WMT

In [47]:
data.iloc[:2,] # for first 2 rows

Company  Price Ticker
0  American Express     95    AXP
1             Cisco     25   CSCO

In [48]:
 data.iloc[2:5,]# 3rd to 5th rows

Company  Price Ticker
2  Walt Disney     85    DIS
3    Microsoft     41   MSFT
4      Walmart     78    WMT

In [49]:
data.iloc[:,0:2] #[rows,columns]

Company  Price
0  American Express     95
1             Cisco     25
2       Walt Disney     85
3         Microsoft     41
4           Walmart     78

In [50]:
data.iloc[:,[0,2]] #1st and 3rd columns

Company Ticker
0  American Express    AXP
1             Cisco   CSCO
2       Walt Disney    DIS
3         Microsoft   MSFT
4           Walmart    WMT

# indexing with loc

In [51]:
data

Company  Price Ticker
0  American Express     95    AXP
1             Cisco     25   CSCO
2       Walt Disney     85    DIS
3         Microsoft     41   MSFT
4           Walmart     78    WMT

In [52]:
data.loc[1]

Company    Cisco
Price         25
Ticker      CSCO
Name: 1, dtype: object

In [53]:
data.loc[[1,2,3,4,5],['Price','Ticker']]

Price Ticker
1   25.0   CSCO
2   85.0    DIS
3   41.0   MSFT
4   78.0    WMT
5    NaN    NaN

In [54]:
data1=data.reindex(index = [0,2], columns = ['Company','Price'])
data1

Company  Price
0  American Express     95
2       Walt Disney     85

In [3]:
import pandas as pd
yrs = [90,91,92,93,94,95]
f4 = {90:8,91:9,92:7,93:8,94:9,95:11}
firm4 = pd.Series(f4,index = yrs)
f5 = {90:14,91:12,92:9,93:13,94:5,95:8}
firm5 = pd.Series(f5,index = yrs)
f6 = {90:8,91:9,92:9,93:10,94:12,95:13}
firm6 = pd.Series(f6,index = yrs)


df = pd.DataFrame(columns = ["Firm1","Firm2","Firm3"], index = yrs)
df.Firm1 = firm4
df.Firm2 = firm5
df.Firm3 = firm6

In [4]:
df

Firm1  Firm2  Firm3
90      8     14      8
91      9     12      9
92      7      9      9
93      8     13     10
94      9      5     12
95     11      8     13

In [5]:
# reindexing 

reindexdf = df.reindex([88,89,90,91,92,93,94,95,96,97,98]
                      ,fill_value =0)
reindexdf

Firm1  Firm2  Firm3
88      0      0      0
89      0      0      0
90      8     14      8
91      9     12      9
92      7      9      9
93      8     13     10
94      9      5     12
95     11      8     13
96      0      0      0
97      0      0      0
98      0      0      0

In [6]:
reindexdf1 = df.reindex([88,89,90,91,92,93,94,95,96,97,98]
                      , method ='ffill' )
reindexdf1

Firm1  Firm2  Firm3
88    NaN    NaN    NaN
89    NaN    NaN    NaN
90    8.0   14.0    8.0
91    9.0   12.0    9.0
92    7.0    9.0    9.0
93    8.0   13.0   10.0
94    9.0    5.0   12.0
95   11.0    8.0   13.0
96   11.0    8.0   13.0
97   11.0    8.0   13.0
98   11.0    8.0   13.0

In [7]:
reindexdf2 = df.reindex([88,89,90,91,92,93,94,95,96,97,98]
                      , method ='bfill')
reindexdf2

Firm1  Firm2  Firm3
88    8.0   14.0    8.0
89    8.0   14.0    8.0
90    8.0   14.0    8.0
91    9.0   12.0    9.0
92    7.0    9.0    9.0
93    8.0   13.0   10.0
94    9.0    5.0   12.0
95   11.0    8.0   13.0
96    NaN    NaN    NaN
97    NaN    NaN    NaN
98    NaN    NaN    NaN

In [8]:
d = { 
    'Name': ['Alisa','Bobby','Jodha','Jack','Raghu','Cathrine',
             'Alisa','Bobby','Kumar','Alisa','Alex','Cathrine'],
    'Age': [26,24,23,22,23,24,26,24,22,23,24,24],
    'Score' : [85,63,55,74,31,77,85,63,42,62,89,77]}

df = pd.DataFrame(d,columns = ['Name','Age','Score'])

In [9]:
df

Name  Age  Score
0      Alisa   26     85
1      Bobby   24     63
2      Jodha   23     55
3       Jack   22     74
4      Raghu   23     31
5   Cathrine   24     77
6      Alisa   26     85
7      Bobby   24     63
8      Kumar   22     42
9      Alisa   23     62
10      Alex   24     89
11  Cathrine   24     77

In [10]:
# drop duplicate

df.drop_duplicates()

Name  Age  Score
0      Alisa   26     85
1      Bobby   24     63
2      Jodha   23     55
3       Jack   22     74
4      Raghu   23     31
5   Cathrine   24     77
8      Kumar   22     42
9      Alisa   23     62
10      Alex   24     89

In [11]:
df.drop_duplicates(keep = 'last') # Retaining last occurance 

Name  Age  Score
2      Jodha   23     55
3       Jack   22     74
4      Raghu   23     31
6      Alisa   26     85
7      Bobby   24     63
8      Kumar   22     42
9      Alisa   23     62
10      Alex   24     89
11  Cathrine   24     77

In [12]:
df.drop([1,2]) # droping a row with row numbers

Name  Age  Score
0      Alisa   26     85
3       Jack   22     74
4      Raghu   23     31
5   Cathrine   24     77
6      Alisa   26     85
7      Bobby   24     63
8      Kumar   22     42
9      Alisa   23     62
10      Alex   24     89
11  Cathrine   24     77

In [13]:
df[df.Name != "Alisa"] #drop using name

Name  Age  Score
1      Bobby   24     63
2      Jodha   23     55
3       Jack   22     74
4      Raghu   23     31
5   Cathrine   24     77
7      Bobby   24     63
8      Kumar   22     42
10      Alex   24     89
11  Cathrine   24     77

In [14]:
df.drop(df.index[2]) # drop using index

Name  Age  Score
0      Alisa   26     85
1      Bobby   24     63
3       Jack   22     74
4      Raghu   23     31
5   Cathrine   24     77
6      Alisa   26     85
7      Bobby   24     63
8      Kumar   22     42
9      Alisa   23     62
10      Alex   24     89
11  Cathrine   24     77

In [15]:
df[:8]

Name  Age  Score
0     Alisa   26     85
1     Bobby   24     63
2     Jodha   23     55
3      Jack   22     74
4     Raghu   23     31
5  Cathrine   24     77
6     Alisa   26     85
7     Bobby   24     63

In [16]:
df[:-3]

Name  Age  Score
0     Alisa   26     85
1     Bobby   24     63
2     Jodha   23     55
3      Jack   22     74
4     Raghu   23     31
5  Cathrine   24     77
6     Alisa   26     85
7     Bobby   24     63
8     Kumar   22     42

In [17]:
df

Name  Age  Score
0      Alisa   26     85
1      Bobby   24     63
2      Jodha   23     55
3       Jack   22     74
4      Raghu   23     31
5   Cathrine   24     77
6      Alisa   26     85
7      Bobby   24     63
8      Kumar   22     42
9      Alisa   23     62
10      Alex   24     89
11  Cathrine   24     77

In [18]:
del df["Age"]

In [19]:

df

Name  Score
0      Alisa     85
1      Bobby     63
2      Jodha     55
3       Jack     74
4      Raghu     31
5   Cathrine     77
6      Alisa     85
7      Bobby     63
8      Kumar     42
9      Alisa     62
10      Alex     89
11  Cathrine     77

In [20]:
d = {'Name':pd.Series(["Alisa","Bobby","Cathrine","Madonna",
               "Rocky","Sebastian","Jaqluine","Rahul","David",
                       "Andrew","Ajay","Teresa"])
    ,'Age':pd.Series([26,27,25,24,31,27,25,33,42,32,51,47]),
    'Score':pd.Series([89,87,67,55,47,72,76,79,44,92,99,69])}

df2 = pd.DataFrame(d)

In [21]:
df2

Age       Name  Score
0    26      Alisa     89
1    27      Bobby     87
2    25   Cathrine     67
3    24    Madonna     55
4    31      Rocky     47
5    27  Sebastian     72
6    25   Jaqluine     76
7    33      Rahul     79
8    42      David     44
9    32     Andrew     92
10   51       Ajay     99
11   47     Teresa     69

In [22]:
df2.sort_values(by="Score") #ascending order

Age       Name  Score
8    42      David     44
4    31      Rocky     47
3    24    Madonna     55
2    25   Cathrine     67
11   47     Teresa     69
5    27  Sebastian     72
6    25   Jaqluine     76
7    33      Rahul     79
1    27      Bobby     87
0    26      Alisa     89
9    32     Andrew     92
10   51       Ajay     99

In [23]:
df2.sort_values(by="Score" ,ascending= 0) #decending order

Age       Name  Score
10   51       Ajay     99
9    32     Andrew     92
0    26      Alisa     89
1    27      Bobby     87
7    33      Rahul     79
6    25   Jaqluine     76
5    27  Sebastian     72
11   47     Teresa     69
2    25   Cathrine     67
3    24    Madonna     55
4    31      Rocky     47
8    42      David     44

In [24]:
df3 = df2.sort_index()
df3

Age       Name  Score
0    26      Alisa     89
1    27      Bobby     87
2    25   Cathrine     67
3    24    Madonna     55
4    31      Rocky     47
5    27  Sebastian     72
6    25   Jaqluine     76
7    33      Rahul     79
8    42      David     44
9    32     Andrew     92
10   51       Ajay     99
11   47     Teresa     69

# Rank

In [37]:
  d = { 
    'Name': ['Alisa','Bobby','Cathrine','Alisa','Bobby','Cathrine',
             'Alisa','Bobby','Cathrine','Alisa','Bobby','Cathrine'],
    'Subject': ["Mathematics","Mathematics","Mathematics","Science","Science"
               ,"Science","History","History","History","Economics","Economics","Economics"],
    'Score': [62,47,55,74,31,77,85,63,42,62,89,85]}
df4 = pd.DataFrame(d ,columns =['Name','Subject','Score'])
df4

Name      Subject  Score
0      Alisa  Mathematics     62
1      Bobby  Mathematics     47
2   Cathrine  Mathematics     55
3      Alisa      Science     74
4      Bobby      Science     31
5   Cathrine      Science     77
6      Alisa      History     85
7      Bobby      History     63
8   Cathrine      History     42
9      Alisa    Economics     62
10     Bobby    Economics     89
11  Cathrine    Economics     85

In [38]:
df4['Score_ranked'] =df["Score"].rank(ascending =1)

In [39]:
df4

Name      Subject  Score  Score_ranked
0      Alisa  Mathematics     62          10.5
1      Bobby  Mathematics     47           5.5
2   Cathrine  Mathematics     55           3.0
3      Alisa      Science     74           7.0
4      Bobby      Science     31           1.0
5   Cathrine      Science     77           8.5
6      Alisa      History     85          10.5
7      Bobby      History     63           5.5
8   Cathrine      History     42           2.0
9      Alisa    Economics     62           4.0
10     Bobby    Economics     89          12.0
11  Cathrine    Economics     85           8.5

In [40]:
df4['Score_ranked'] =df["Score"].rank(ascending =0)

In [41]:
df4

Name      Subject  Score  Score_ranked
0      Alisa  Mathematics     62           2.5
1      Bobby  Mathematics     47           7.5
2   Cathrine  Mathematics     55          10.0
3      Alisa      Science     74           6.0
4      Bobby      Science     31          12.0
5   Cathrine      Science     77           4.5
6      Alisa      History     85           2.5
7      Bobby      History     63           7.5
8   Cathrine      History     42          11.0
9      Alisa    Economics     62           9.0
10     Bobby    Economics     89           1.0
11  Cathrine    Economics     85           4.5

In [ ]:
Rank     Dense_rank
A 1         1

B 2         2

C 2         2

D 4         3

In [43]:
df4['Score_ranked'] =df["Score"].rank(ascending =0, method ='dense')

In [44]:
df4

Name      Subject  Score  Score_ranked
0      Alisa  Mathematics     62           2.0
1      Bobby  Mathematics     47           5.0
2   Cathrine  Mathematics     55           7.0
3      Alisa      Science     74           4.0
4      Bobby      Science     31           9.0
5   Cathrine      Science     77           3.0
6      Alisa      History     85           2.0
7      Bobby      History     63           5.0
8   Cathrine      History     42           8.0
9      Alisa    Economics     62           6.0
10     Bobby    Economics     89           1.0
11  Cathrine    Economics     85           3.0

In [49]:
# Hierarchical indexing and Multiple index in python
    d = { 
    'Name': ['Alisa','Bobby','Cathrine','Alisa','Bobby','Cathrine',
             'Alisa','Bobby','Cathrine','Alisa','Bobby','Cathrine'],
    'Exam':['Semester_1','Semester_1','Semester_1','Semester_1','Semester_1','Semester_1',
           'Semester_2','Semester_2','Semester_2','Semester_2','Semester_2','Semester_2'],
      'Subject': ["Mathematics","Mathematics","Mathematics","Science","Science"
               ,"Science","History","History","History","Economics","Economics","Economics"],
    'Score': [62,47,55,74,31,77,85,63,42,62,89,81]}

In [50]:
df5 = pd.DataFrame(d , columns =["Name","Exam","Subject","Score"])
df5

Name        Exam      Subject  Score
0      Alisa  Semester_1  Mathematics     62
1      Bobby  Semester_1  Mathematics     47
2   Cathrine  Semester_1  Mathematics     55
3      Alisa  Semester_1      Science     74
4      Bobby  Semester_1      Science     31
5   Cathrine  Semester_1      Science     77
6      Alisa  Semester_2      History     85
7      Bobby  Semester_2      History     63
8   Cathrine  Semester_2      History     42
9      Alisa  Semester_2    Economics     62
10     Bobby  Semester_2    Economics     89
11  Cathrine  Semester_2    Economics     81

In [51]:
df6 = df5.set_index(["Exam","Subject"])
df6

Name  Score
Exam       Subject                     
Semester_1 Mathematics     Alisa     62
           Mathematics     Bobby     47
           Mathematics  Cathrine     55
           Science         Alisa     74
           Science         Bobby     31
           Science      Cathrine     77
Semester_2 History         Alisa     85
           History         Bobby     63
           History      Cathrine     42
           Economics       Alisa     62
           Economics       Bobby     89
           Economics    Cathrine     81

In [52]:
df6.index

MultiIndex(levels=[['Semester_1', 'Semester_2'], ['Economics', 'History', 'Mathematics', 'Science']],
           labels=[[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1], [2, 2, 2, 3, 3, 3, 1, 1, 1, 0, 0, 0]],
           names=['Exam', 'Subject'])

In [53]:
# Swaping the columns in the hierachical indexing
df6.swaplevel("Subject","Exam")

Name  Score
Subject     Exam                       
Mathematics Semester_1     Alisa     62
            Semester_1     Bobby     47
            Semester_1  Cathrine     55
Science     Semester_1     Alisa     74
            Semester_1     Bobby     31
            Semester_1  Cathrine     77
History     Semester_2     Alisa     85
            Semester_2     Bobby     63
            Semester_2  Cathrine     42
Economics   Semester_2     Alisa     62
            Semester_2     Bobby     89
            Semester_2  Cathrine     81

In [55]:
import numpy as np
df7 = pd.DataFrame(np.random.rand(5,3), index = ["a","c","e","g","i"],
                      columns = ["one","two","three"])

In [56]:
df7

one       two     three
a  0.428356  0.332568  0.806740
c  0.796805  0.151877  0.447670
e  0.890991  0.005200  0.165176
g  0.668278  0.957845  0.337943
i  0.166005  0.635441  0.030769

In [57]:
df7 = df7.reindex(["a","b","c","d","e","f","g","h","i"])

In [58]:
df7

one       two     three
a  0.428356  0.332568  0.806740
b       NaN       NaN       NaN
c  0.796805  0.151877  0.447670
d       NaN       NaN       NaN
e  0.890991  0.005200  0.165176
f       NaN       NaN       NaN
g  0.668278  0.957845  0.337943
h       NaN       NaN       NaN
i  0.166005  0.635441  0.030769

In [59]:
df7["one"].isnull() # for null values

a    False
b     True
c    False
d     True
e    False
f     True
g    False
h     True
i    False
Name: one, dtype: bool

In [60]:
df7["one"].notnull()

a     True
b    False
c     True
d    False
e     True
f    False
g     True
h    False
i     True
Name: one, dtype: bool

In [61]:
df8=df7.fillna(method='ffill')
df8

one       two     three
a  0.428356  0.332568  0.806740
b  0.428356  0.332568  0.806740
c  0.796805  0.151877  0.447670
d  0.796805  0.151877  0.447670
e  0.890991  0.005200  0.165176
f  0.890991  0.005200  0.165176
g  0.668278  0.957845  0.337943
h  0.668278  0.957845  0.337943
i  0.166005  0.635441  0.030769

In [62]:
df7

one       two     three
a  0.428356  0.332568  0.806740
b       NaN       NaN       NaN
c  0.796805  0.151877  0.447670
d       NaN       NaN       NaN
e  0.890991  0.005200  0.165176
f       NaN       NaN       NaN
g  0.668278  0.957845  0.337943
h       NaN       NaN       NaN
i  0.166005  0.635441  0.030769

In [63]:
df7.dropna()

one       two     three
a  0.428356  0.332568  0.806740
c  0.796805  0.151877  0.447670
e  0.890991  0.005200  0.165176
g  0.668278  0.957845  0.337943
i  0.166005  0.635441  0.030769

In [64]:
df7.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [a, b, c, d, e, f, g, h, i]

In [65]:
df9 = pd.DataFrame({"one": [10,20,30,40,50,2000], "two":[1000,0,30,40,50,60]})
df9

one   two
0    10  1000
1    20     0
2    30    30
3    40    40
4    50    50
5  2000    60

In [66]:
df9.replace({1000:10,2000:60})

one  two
0   10   10
1   20    0
2   30   30
3   40   40
4   50   50
5   60   60

# Merge(joins)

In [67]:
import pandas as pd


In [69]:
left_frame = pd.DataFrame({"Key":range(5),
                          "left_value":["a","b","c","d","e"]})

right_frame = pd.DataFrame({"Key":range(2,7),
                          "right_value":["a","b","c","d","e"]})



print(left_frame)
print("\n")
print(right_frame)

   Key left_value
0    0          a
1    1          b
2    2          c
3    3          d
4    4          e


   Key right_value
0    2           a
1    3           b
2    4           c
3    5           d
4    6           e


In [71]:
# inner join
pd.merge(left_frame,right_frame , on ="Key" , how ="inner")

Key left_value right_value
0    2          c           a
1    3          d           b
2    4          e           c

In [72]:
# left join
pd.merge(left_frame,right_frame , on ="Key" , how ="left")

Key left_value right_value
0    0          a         NaN
1    1          b         NaN
2    2          c           a
3    3          d           b
4    4          e           c

In [73]:
# right join 
pd.merge(left_frame,right_frame , on ="Key" , how ="right")

Key left_value right_value
0    2          c           a
1    3          d           b
2    4          e           c
3    5        NaN           d
4    6        NaN           e

In [74]:
# Outer join 
pd.merge(left_frame,right_frame , on ="Key" , how ="outer")

Key left_value right_value
0    0          a         NaN
1    1          b         NaN
2    2          c           a
3    3          d           b
4    4          e           c
5    5        NaN           d
6    6        NaN           e

In [75]:
#concatenate
pd.concat([left_frame,right_frame])

Key left_value right_value
0    0          a         NaN
1    1          b         NaN
2    2          c         NaN
3    3          d         NaN
4    4          e         NaN
0    2        NaN           a
1    3        NaN           b
2    4        NaN           c
3    5        NaN           d
4    6        NaN           e

In [76]:
 pd.concat([left_frame,right_frame],axis = 1)

Key left_value  Key right_value
0    0          a    2           a
1    1          b    3           b
2    2          c    4           c
3    3          d    5           d
4    4          e    6           e